name: Recent Bot Update
on:
  schedule:
    - cron: '*/30 9-13 * * 1-5'
    - cron: '*/30 5-10 * * 0,6'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 소스코드 가져오기
        uses: actions/checkout@v4

      - name: Node.js 세팅
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 패키지 설치
        run: npm install

      - name: 리센트 크롤러 실행
        run: npm run update:recent

      - name: 깃허브에 데이터 자동 저장
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "봇: 최근 타석 실시간 업데이트" && git push)